apiVersion: v1
kind: ReplicationController
metadata:
  name: boinc-workers
spec:
  selector:
    name: boinc-workers
    version: v1
  template:
    metadata:
      labels:
        name: boinc-workers
        version: v1
        priority: charity
    spec:
      containers:
      - image: techwolf12/boinc:stable
        name: boinc-workers
        #args: ["-attach_project", <BoincProjectServer>, <Account Key>]
        args: ["-attach_project", "boinc.bakerlab.org/rosetta/", "<Account key>"]
